systemd/casync

- src/casync-tool.c
- src/casync.c
- src/casync.h
This makes sure that sensitive files stay sensitive.
> Create .catar files with the permission of origin

- src/caencoder.c
- src/util.h
When operating on a block device, let's read the first 4 bytes and see if we
can detect a file system. If that's the case, determine the number of bytes
worth reading from that source.
This patch implements the squashfs reader only, but other types could easily
be added.
> caencoder: add basic file system header parser

- src/caencoder.c
squashfs images are usually aligned to 4096 bytes unless explicitly
stated otherwise. In the latter case, however, seeding the last bytes
of the block device doesn't harm, so let's always do that.
> encoder: fix two image size detection issues

- meson.build
- meson_options.txt
- src/cafuse.h
- src/casync-tool.c
- src/meson.build
No autodetection is performed. -Dfuse=false can be used to disable fuse
support.
fuse-related options are not advertised, but they are still understood
(and fail immediately).
> meson: make fuse support optional

- src/casync-tool.c
Looks like it was broken since 88b94e1
```
../src/casync-tool.c: In function ‘verb_list’:
../src/casync-tool.c:1996:51: error: storage size of ‘tm’ isn’t known
struct tm tm;
^~
../src/casync-tool.c:1999:45: error: implicit declaration of function ‘localtime_r’ [-Werror=implicit-function-declaration]
if (localtime_r(&t, &tm) &&
^~~~~~~~~~~
../src/casync-tool.c:1999:45: warning: nested extern declaration of ‘localtime_r’ [-Wnested-externs]
../src/casync-tool.c:2000:45: error: implicit declaration of function ‘strftime’ [-Werror=implicit-function-declaration]
strftime(d, sizeof(d), "%Y-%m-%d %H:%M:%S", &tm) > 0)
^~~~~~~~
../src/casync-tool.c:2000:45: warning: incompatible implicit declaration of built-in function ‘strftime’
../src/casync-tool.c:2000:45: note: include ‘<time.h>’ or provide a …
```
> tool: fix compilation error

- src/caorigin.h
Fixes build failure on 32 bit:
```
../src/caorigin.c:208:5: error: conflicting types for ‘ca_origin_advance_bytes’
int ca_origin_advance_bytes(CaOrigin *origin, uint64_t n_bytes) {
^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/caorigin.c:1:0:
../src/caorigin.h:29:5: note: previous declaration of ‘ca_origin_advance_bytes’ was here
int ca_origin_advance_bytes(CaOrigin *origin, size_t n_bytes);
```
> casync: Fix declaration of ca_origin_advance_bytes

- README.md
borg is [under the hood](http://borgbackup.readthedocs.io/en/latest/internals.html) very similar to casync;
- packs metadata into a stream, like tar and casync
- metadata stream is chunked and globally deduplicated
- file data is chunked and globally deduplicated
- also uses buzhash (though I'm not 100% convinced it's a good choice for a new project,
it's quite limited in terms of performance — I've done only limited testing on this idea
but giving up byte-granularity and instead using 4-8 byte granularity is a rather large performance
improvement, with at least in my tests little impact on deduplication).
At this time it is still _sufficient_ though, at least in a multi-threaded context.
- uses SHA-256 (in 1.0)... it'd probably be better to use something different
in a new project, e.g. …
> README: add borg

- test/test-script.sh.in
test-script.sh would fail when the top source dir was called e.g. casync-1.
> tests: fix tests when the source directory is not called "casync"

- test/semaphore-run
Current master produces a lot of type warnings on 32 bit, and tests fail
with "Failed to run synchronizer: Bad message".
Add a 32 bit (i386 Debian architecture) (cross-)build and test run to
uncover these.
> tests: Add 32 bit run to semaphore

- meson.build
This completes a067f9d94 "Add TAGS target".
Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>
> meson: support other tag systems like ctags

- .gitignore
- meson.build
This is confusing, but etags(1) is pretty clear:
- emacs expects TAGS file in etags format
- vi expects tags file in ctags format
and automake docs are pretty clear too:
- tags generates TAGS file
- ctags generates tags file
> meson: use TAGS for the etags output

- TODO
- doc/casync.rst
- meson.build
- src/cachunkid.h
- src/cadecoder.c
- src/cadecoder.h
- src/cadigest.c
- src/cadigest.h
- src/caencoder.c
- src/caformat-util.c
- src/caformat-util.h
- src/caformat.h
- src/caremote.c
- src/caremote.h
- src/caseed.c
- src/casync-tool.c
- src/casync.c
- test/http-server.py
- test/test-caencoder.c
- test/test-calc-digest.c
- test/test-casync.c
- test/test-nbd.sh.in
- test/test-script-sha256.sh.in
- test/test-script.sh.in
sha256 remains supported, via --digest=sha256, as it has benefits when
focussing on 32bit systems, but the new default is sha512/256, as it is
substantially faster on 64bit systems.
The used hash algorithm is encoded in the feature flags field in the
index and archive files, so that directing casync onto index or archive
files is enough for it to determine how to encode/look for chunks.
> casync: use sha512/256 as hash function by default

- src/util.h
```casync``` was recently uploaded to Debian for the first time [1].
After the buildds finished building the packages, I noticed that the definitions for ```__NR__renameat2``` is missing for multiple architectures. This is fixed in this PR.
Adrian
> [1] https://packages.qa.debian.org/c/casync.html
> [2] https://buildd.debian.org/status/package.php?p=casync&suite=sid
> Define __NR_renameat2 for multiple architectures

- meson.build
2 minutes is too short for slow architectures
---
Please don't merge until https://buildd.debian.org/status/package.php?p=casync is free of timeout errors, it may be that 3 is still not enough.
> Bump test timeouts to 3 minutes.

- src/canbd.c
Closes: https://github.com/systemd/casync/issues/71
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>
> include sys/uio.h to get declaration of writev()

- src/cadecoder.c
- src/caencoder.c
- src/caremote.c
Fixes #73.
The output is pretty crappy:
$ build/casync --with=selinux make ...
Failed to run synchronizer: Operation not supported
but that's being tracked as #44.
> Fix build without selinux and refuse --with=selinux when compiled without

- src/cafuse.c
CA_SYNC_POLL indicates that more data needs to be received. This will
occur for example, when the read() call in ca_remote_read() returns
EAGAIN.
Returning 0 from iterate_until_file() instead indicates that reading
file data was completed, successfully. Returning this in case of
CA_SYNC_POLL will result in file data not being initialized correctly.
In case of a getattr() fuse call, for example, casync will always return
a directory entry for the first call, no matter if the requested entry
exists or not.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
> cafuse: do not return from iterate_until_file() in CA_SYNC_POLL case

- doc/casync.rst
For code quoting previous paragraph needs to end in :: apparently.
This was flagged by lintian, which flagged the manpage as borked.
> Fix formatting error

- src/caseed.c
- src/caseed.h
- src/casync.c
When user set a chunk_size, chunker.discriminator should be re-caculated
with new chunk_size. Elsewise, Local seed cache can't be used to extract
remote server.
> Fix seed chunker discriminator not set

- mkosi.default
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> mkosi: add missing build dependencies

- src/casync-tool.c
Luckily the default type is the same, but of course this results
in a warning. Introduced in dfc994ad07.
> casync-tool: fix warnings about missing type declaration

- src/cadecoder.c
When mounting a casync .caidx describing a directory that contains a file
system image while using the block device `/dev/mmcblk0p1` as seed, casync
fails when accessing this image:
> casync mount http://127.0.0.1:8080/packed-directory.caidx --seed=/dev/mmcblk0p1 /mnt/test
> user@device:~# md5sum /mnt/test/rootfs-image.ext4
> md5sum: can't read '/mnt/test/rootfs-image.ext4': Invalid argument
The trigger for this error is a sanity check in `ca_decoder_put_data()`:
if (origin && origin->n_bytes != size)
return -EINVAL;
It checks that the methods `size` argument equals the `n_bytes` member of
`CaOrigin` argument `origin` if provided.
This check is triggered in method `ca_sync_process_decoder_request()` when
`ca_sync_get()` returns data received from `ca_sync_get_local()` and thus has
an …
> src: cadecoder: remove origin size sanity check in ca_decoder_put_data()

- meson.build
struct ZSTD_CStream was introduced in version 0.8.1.  Prefer failure
during configure stage instead of compilation if a too old version of
zstd is installed.
Signed-off-by: Gunnar Andersson <gandersson@genivi.org>
> meson.build: minimum required version for zstd

- src/caremote.c
- src/caremote.h
- src/casync-http.c
Between caremote and casync-http, URL arguements are accessed by
relative offset. To readability, the offsets should be enumeration.
> caremote: Add enum for readability of caremote URL arguments

- TODO
- meson.build
- meson_options.txt
- src/cafuse.c
- src/canbd.c
- src/canbd.h
- src/casync-tool.c
- src/log.c
- src/udev-util.h
- test/semaphore-run
- test/test-script.sh.in
This fixes #114 properly, by waiting with udev until the device node appeared and has been probed as valid.
Also, a number of other fixes
> properly wait for "casync mkdev" nbd devices to appear with udev

- meson.build
setting udevdir implicitly always added udev as build dependency, making
it inappropriate for host tool builds.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
> meson.build: make udev really optional

- src/cadecoder.c
- src/caencoder.c
- src/chattr.c
- src/chattr.h
- src/meson.build
- src/rm-rf.c
Let's split out the code for setting DOS and Linux file attributes into
chattr.[ch], and clean it up a bit.
Most importantly, don't choke if either ioctl returns EINVAL, and just
take that as the backing file system not supporting these ioctls, which
ntfs3g doesn't appear to do. I am pretty sure its a bug in ntfs3g that
they don't return sane error codes for these ioctls, but given that this
code is widely deployed deal with it.
Fixes: #115 #116
> chattr: rework DOS and Linux file attribute logic

- src/cadecoder.c
If for example a catar file contains a file whose owner is not existing
on the target system, getpwnam_r() will return 0 and set pw to NULL.
In the former return code handling, only r == 0 with pw *not* being NULL
was checked and properly handled.
For all other cases we fell into the error return conditional which only
checked for getting ERANGE and otherwise makes negative error numbers
from positive ones or returns -ESRCH for 'error' numbers being
non-negative.
Thus, for the case described above, we fell into the return code check
with having a non-negative return code '0' and thus simply returned
-ESRCH ('No such process') from name_to_uid() which is definitely the
wrong conclusion and leads to confusing error messages such as:
> Failed to run synchronizer: No such process
Instead we …
> src/cadecoder: fix getpwnam_r() and getgrnam_r() return code handling

- src/caformat.h
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
> src: caformat.h: do not set selinux flags by default when compiled without selinux

- src/casync-tool.c
I think this is a typo / copy paste mistake. Unfortunately I don't know how to trigger this message.
> Fix error message when setting max chunk size fails

- test/http-server.py
- Files: test/http-server.py
- Changes: Import re-ordered
According to PEP8's import section (Style Guide for Python) Imports should usually be on separate lines and order by alphabetical names
---
Acceptable:
```python
import os
import sys
```
Not Acceptable:
```python
import os,sys
```
---
> [test/http-server.py] Imports re-ordered

- src/util.h
Allows compilation on Void Linux x86_64-musl arch.
> src/util.h: add missing sys/types.h include for mode_t in musl systems

- src/cachunker.c
For some reason, in F28, we get 4095 as the result of the expression.
I would expect to always get 4096, but in principle 4096- 1/2 ulp is also a
correct answer, and then when truncating, we would get 4095. So let's round the
result to get the expected answer.
Fixes #133.
> cachunker: round the expected average chunk size

- meson.build
We don't do much floating point processing, and given that #133 has
shown that the inaccuracies introduced by -ffast-math have an effect on
us, let's sidestep the whole issue and turn off the whole thing for us.
After all reproducibility is supposed to be a big thing in casync, hence
we should really come to the same results on all archs, and all
compilers and all versions thereof.
See: #133
> meson: drop -ffast-math from gcc options

- src/casync-tool.c
HAVE_UDEV is always defined in config.h as 1 or 0 so the check for udev
support must use 'if' directive instead of 'ifdef'.
Signed-off-by: Mihai Serban <mihai.serban@gmail.com>
> casync-tool: Fix compile without udev support

- src/cadecoder.c
This addresses issue #88 (https://github.com/systemd/casync/issues/88) "extracting char devices: Failed to run synchronizer: Operation not supported".
When extracting character or block devices, fchmodat() is called with flag AT_SYMLINK_NOFOLLOW.
According to the documentation (man page), this is not supported and hence returns ENOTSUP.
The only supported flag is 0.
> AT_SYMLINK_NOFOLLOW in fchmodat() is not supported.

- meson.build
As described in #166, -D_GNU_SOURCE needs to be passed to the meson function
availability checker. h/t to @tomeon for providing a link to the solution as
well.
Fixes #166
> meson.build: pass -D_GNU_SOURCE when checking for functions

- src/util.c
On centos7 (gcc 4.8.5) this include is needed and not derived otherwise
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> util: missing include for falloc

- meson.build
Building on centos7 with libcurl 7.29 available
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> meson: loosen libcurl version requirement

- meson.build
- meson_options.txt
Also aligns logic to how its handled in https://github.com/libfuse/libfuse/
> meson.build: allow udevrulesdir to be set as option

- meson.build
The config.h which we generate doesn't apply for checks and those
functions are available only when _GNU_SOURCE is defined.
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> build: check for renameat2()/copy_file_range() with _GNU_SOURCE

- src/cachunker.c
Use a simple fixed size chunker if the user sets chunk size to a fixed value,
for example: --chunk-size=262144:262144:262144
This is useful for VM images, because it is multiple times faster than
rolling window.
> cachunker.c: implement fixed size chunker

- test/test-cache.sh.in
Some build environments check out source code as readonly. When it is copied into the scratch dir for the test-cache test, the files are copied as readonly, and appending to README.md in the scratch directory fails. So first make the file writable before appending to it.
> Ensure scratch file is writable

- src/casync-tool.c
This commit adds percentage to the output of `casync extract`, to easily see the distribution of incoming chunks among local store, local seed and remote store.
The new output looks like that:
$ casync extract -v test.caibx yop.img
Zero bytes written as sparse files: 7.3G
Bytes cloned through reflinks: 0B
Chunk requests fulfilled from local store: 127661 (100%)
Bytes used from local store: 13.9G (100%)
Chunk requests fulfilled from local seed: 0 (0%)
Bytes used from local seed: 0B (0%)
Chunk requests fulfilled from remote store: 0 (0%)
Bytes used from remote store: 0B (0%)
(see #180 for original discussion)
> Display percentage in casync extract summary

- src/casync-tool.c
The total number can be zero even if we did some operation, and then we'd
divide by zero, crashing immediately with FPE.
> Do not divide by zero when displaying percentages

- src/casync-http.c
With this commit, one must set casync log level to debug in order to see
each downloaded chunks (additionally to setting the verbose flag).
casync -v --log-level=debug extract ...
Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>
> casync-http: Log downloaded chunks with debug level (was info)

- doc/casync.rst
- src/casync-tool.c
- src/log.c
- src/log.h
Now the log level can be set with:
casync --log-level debug|info|error ...
This command-line argument overrides the environment variable
`CASYNC_LOG_LEVEL`.
Closes: #185
Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>
> Add --log-level option

- src/cadecoder.c
- src/caencoder.c
- src/cafuse.c
- src/calocation.c
- src/canbd.c
- src/caremote.c
- src/caseed.c
- src/caseed.h
- src/casync-tool.c
- src/casync.c
- src/casync.h
- src/meson.build
- src/parse-util.c
- src/time-util.c
- src/time-util.h
- src/util.c
- src/util.h
- test/notify-wait.c
- test/test-cachunker-histogram.c
- test/test-cadigest.c
- test/test-calocation.c
This MR adds the following lines to `casync extract` verbose output:
Time spent seeding: 6.529038 secs (9%)
Time spent decoding: 63.074518 secs (90%)
Total extract time: 69.623602 secs (00:01:10)
----
Here are a few comments:
- time measurements are done with `now()`, which provides nanoseconds precision. However in the output I round to micro-seconds, as I think displaying nanoseconds is overkill.
- I used the words `seeding` and `decoding` to describe the two main steps of `casync extract`. "Seeding" was obvious. "Decoding" seems a good word to me, but feel free to propose something else.
> casync extract: Add time statistics

- src/cachunk.c
As compression is always enabled, we are more likely to find a compressed chunk in the repo than an uncompressed one.
(just for performance)
> ca_chunk_file_test: check compressed file before uncompressed one

- src/log.c
If `format` already ends with `\n`, then `fmt` was not initialized, and used all the same. Funny that the compiler didn't catch it.
> Fix uninitialized variable in log_fullv

- src/cadecoder.c
We erroneously use the st_dev value in place of the magic value if the st_dev value is cached. This causes problems extracting trees containing subvolumes.
Fixes #237.
> Fix btrfs subvolume detection

- src/caprotocol.h
The commit specifies the name of the server (S) that is later used in
the description.
Also, it adds the missing 'i' in the word 'finIshed' and fixes the
multi-line comment by removing the unnecessary leading '* ' before
closing the comment.
> caprotocol: fix typo in protocol description

- src/cautil.c
- src/util.c
There is a small typo in src/cautil.c, src/util.c.
Should read `distinguish` rather than `distuingish`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, distuingish -> distinguish

- src/castore.c
castore.c unconditioanlly includes lzma.h, but lzma support if optional.
Furthermore, castore.c does not need anything from lzma.h.
Drop the include altogether.
> castore: fix build without lzma or xz

- src/casync-http.c
libcurl ignores the ~/.netrc file by default.
This makes the use of the ~/.netrc file optional; the information in the
URL is preferred.
> casync-http: make the use of .netrc optional

- meson.build
- src/canbd.c
- src/caremote.c
- src/casync.c
- src/util.c
- test/notify-wait.c
- test/test-caencoder.c
This pull request fixes some issues I ran into when trying to build casync against musl libc (though not all, a few still remain).
I believe these changes should be uncontroversial.
> Minor portability fixes

- src/caremote.c
- src/caremote.h
- src/casync-http.c
- src/casync-tool.c
- src/casync.c
- src/casync.h
This patchset adds some verbosity to the protocol helpers.
The two first pathes are minor changes.
The third patch propagates the `--log-level` options given to `casync` to `casync-http`. It is based on what is already done for option `--rate-limit-bps`.
The last patch adds some verbosity in libcurl. The HTTP request and response headers are printed to stderr.
```
$ casync --log-level debug extract http://localhost/file.caibx /dev/loop0
Acquiring http://localhost/file.caibx...
*   Trying ::1:80...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET /file.caibx HTTP/1.1
Host: localhost
Accept: */*
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Accept-Ranges: bytes
< ETag: "1904834653"
< Last-Modified: Mon, 17 Jun 2019 …
```
> Propagate log-level to protocol helpers

- doc/casync.rst
- src/casync-tool.c
While I was working on completing the bash completion script (see #215), I found out that both list and mtree commands have an incomplete usage.
Both handle a second optional argument *PATH*, as the stat command does.
Correct me if I am wrong.
---
The three commands list, mtree and stats are dispatched to the same
function: verb_list().
Thus, they share the same command line interface:
casync list|mtree|stat [ARCHIVE|ARCHIVE_INDEX|DIRECTORY] [PATH]
However, in the end, the output is different.
This commit fixes the help usage and the man page for both commands list
and mtree.
> Fix usage for list and mtree commands

- shell-completion/bash/casync
This PR improves the support for bash completion of `casync`.
It supports for options and handles per-command completion.
> Improve bash completion

- src/util.h
A client may avoid a login prompt when accessing a basic access authentication by prepending username:password@ to the hostname in the URL. This PR adds support for unsafe ASCII characters in username and password.
P.S. I know that this feauture has been deprecated by RFC 3986, but many users use it.
> src/util: Add Basic Authorization URL Encoding Support

- src/casync-http.c
Hi,
This is a proposal to fix the issue mentioned in the second commit. This solution as a drawnback
There is an alternative solution. It consists in fixing the issue in casync process by updating the state machine to download the file after seeding.
In my solution, the size of the index is limited to `CA_PROTOCOL_SIZE_MAX` (16*1024*1024). Is it enough for an index file?
@poettering, @keszybz, what do you think?
> Fix curle partial file on downloading index

- src/casync-tool.c
Those log_error_errors() calls should return.
> casync-tool: fix missing return statement with log_error_errno

- src/caencoder.c
Since glibc 2.36, the mount.h is no longer compatible with the linux mount.h and inclusion of both will cause definition conflicts:
https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E
Fix this by removing inclusion of `sys/mount.h` since inclusion of `linux/fs.h` already pulls in `linux/mount.h`.
> caencoder: remove sys/mount.h to fix build against glibc 2.36

- src/compressor.h
Fix the following build failure with gcc >= 13:
```
In file included from ../src/compressor.c:3:
../src/compressor.h:59:59: error: unknown type name 'size_t'
59 | int compressor_input(CompressorContext *c, const void *p, size_t sz);
|                                                           ^~~~~~
../src/compressor.h:19:1: note: 'size_t' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
18 | #include "cacompression.h"
+++ |+#include <stddef.h>
19 |
```
Fixes:
- http://autobuild.buildroot.org/results/ab08f3b90d253db45643dd058b80ae1dd5f49d0f
> src/compressor.h: fix build with gcc >= 13
