- src/caencoder.c
This image format is generated by the skales tool and read by the
LittleKernel (LK) bootloader. See
git://codeaurora.org/quic/kernel/skales
> caencoder: add length detection for android boot images

- src/cadecoder.c
- src/caencoder.c
- src/caseed.c
- src/casync-tool.c
Trivial changes for mem leak, OOM error path, and warnings on new glibc
> Misc fixes

- src/util.h
Value taken from
https://fedora.juszkiewicz.com.pl/syscalls.html
> util: hook up renameat2 for aarch64

- src/casync-tool.c
When extracting, and the file passed as output file does already exist, use
it as extra seed automatically. This way, a file can be extracted, and only
parts that are missing are taken from the store. If the store is remote,
this will save network bandwidth.
Maybe that behavior can be made optional in the future.
> casync-tool: add existing file as seed during extract

- test/semaphore-run
This builds the package and runs tests as user and root.
> tests: Add semaphore run script

- src/cadecoder.c
- src/caremote.c
- src/util.h
- test/test-cadigest.c
most likely a fix for #60, plus other fixes. And a replacement for #63 using the right destructor for ca_digest
> Some ubsan and absan fixes

- src/cadecoder.c
Noticed by dcb314. Fixes #117.
> cadecoder: fix data size check

- src/cadecoder.c
> Revert "src/cadecoder: fix getpwnam_r() and getgrnam_r() return code handling"

- src/casync-http.c
When hitting "Ctrl-C" during `casync extract`, the casync-http worker receives a signal which is not handled, resulting in an unclean exit: the `/var/tmp/<...>.carem` directory is not deleted.
This commit adds basic signal handling for exit signals, ensuring clean exit and deletion of the temporary work directory in `/var/tmp`.
> Add exit signal handler to casync-http

- src/casync-http.c
This patch implements a retry in casync-http, in the case where `curl_easy_perform` returns `CURLE_COULDNT_CONNECT`.
Issue (how to reproduce)
------------------------
Guest is a QEmu VM, host is Debian testing.
$ qemu-system-x86_64 -enable-kvm \
-nic user,hostfwd=tcp::2222-:22 \
...
Python3 http server is running on the host.
$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
CASync is used on the guest.
$ casync --version
casync 2
$ apt-cache show casync | grep ^Version
Version: 2+20180321-2
With this setup, 'casync extract' fails consistently with:
$ casync extract http://10.0.2.2:8000/rootfs.img.caibx /dev/sda6
Failed to acquire http://10.0.2.2:8000/default.castr/890d/890d...0c74a.cacnk
Failed to run synchronizer: Broken pipe
Debug
-----
Investigation …
> casync-http: retry when curl fails to connect

- src/util.h
This is a copy of
https://github.com/systemd/systemd/commit/66a64081f82dfad90f2f9394a477820a2e3e6510.
> Copy FOREACH_STRING fix from systemd

- meson.build
- meson_options.txt
- src/cachunk.c
- src/cacompression.h
- src/castore.c
- src/casync-tool.c
- src/casync.c
- src/compressor.c
- src/compressor.h
- test/fuzz/fuzz-compress.c
- test/fuzz/fuzz-main.c
- test/fuzz/fuzz.h
- test/fuzz/meson.build
- test/meson.build
- test/test-script.sh.in
- tools/oss-fuzz.sh
A PR for oss-fuzz is also needed. I'll have that ready.
As mentioned in the commit message for 1/6, the error reporting when compressors are compiled-out is not very good. But I'd prefer to merge this as is, and work on the reporting later, because I think it's a major undertaking on its own. Right now, the error reporting is almost non-existent.
> oss-fuzz hookup

- .dir-locals.el
- .editorconfig
- .vimrc
(nothing magic, just a refresh from systemd)
> editor: update formatting rules from systemd

- src/util.c
like on some fuse FS
Allow casync to be run on some rclone mount for example.
> rename_noreplace: use renameat if linkat isn't supported

- test/test-casync.c
Minor fixes in `test/test-casync.c`
> Remove casync-test data after use

- meson.build
- meson_options.txt
- shell-completion/bash/casync
- shell-completion/bash/meson.build
This is not complete, it only provides commands, not options, but it's better than nothing I guess?
> Add basic bash completion

- mkosi.default
Forgot to update this to Fedora31 when I did systemd and mkosi
> Update to Fedora31

- src/cadecoder.c
> Correctly reset setuid/setgid bit

- README.md
> Updated required dependencies

- src/caencoder.c
Don't exclude files (or even read in `.caexclude`) when `--exclude-file=no` option is set.
Otherwise, there's an issue where files can be incorrectly excluded when calculating a digest (e.g. `casync --exclude-file=no digest /some/dir` where `/some/dir` has a `.caexclude`) or when outputting a `list` or `mtree`.
> Respect --exclude-file=no option

- src/cachunker.c
The first `c->chunk_size_min - CA_CHUNKER_WINDOW_SIZE` bytes don't contribute to the result, so we don't need to hash them. This improves chunker throughput by about 16% (216 MiB/s -> 250MiB/s) in my benchmarks.
> cachunker: don't scan bytes we can't break on
